//
// **** AUTOMATICALLY GENERATED BY mk-node-decls.pl -- DO NOT EDIT ****
//
#include <cdk/ast/all.h>

#ifdef __NODE_DECLARATIONS_ONLY__

namespace gr8 {
class evaluation_node; 
class if_else_node; 
class if_node; 
class print_node; 
class identity_node; 
class read_node; 
class stop_node; 
class sweeping_from_to_by_do_node; 
class block_node; 
class null_node; 
class again_node; 
class return_node; 
class index_node; 
class memory_allocation_node; 
class function_declaration_node; 
class address_of_node; 
class function_define_node; 
class function_call_node; 
class variable_declaration_node; 

} // namespace gr8

#else /* !defined(__NODE_DECLARATIONS_ONLY__) */

#ifndef __AUTOMATIC_gr8_NODE_ALLNODES_H__
#define __AUTOMATIC_gr8_NODE_ALLNODES_H__

#include "ast/evaluation_node.h"
#include "ast/if_else_node.h"
#include "ast/if_node.h"
#include "ast/print_node.h"
#include "ast/identity_node.h"
#include "ast/read_node.h"
#include "ast/stop_node.h"
#include "ast/sweeping_from_to_by_do_node.h"
#include "ast/block_node.h"
#include "ast/null_node.h"
#include "ast/again_node.h"
#include "ast/return_node.h"
#include "ast/index_node.h"
#include "ast/memory_allocation_node.h"
#include "ast/function_declaration_node.h"
#include "ast/address_of_node.h"
#include "ast/function_define_node.h"
#include "ast/function_call_node.h"
#include "ast/variable_declaration_node.h"


#endif /* !defined(__AUTOMATIC_gr8_NODE_ALLNODES_H__) */

#endif /* !defined(__NODE_DECLARATIONS_ONLY__) */
